title: 라프의 실험일지
description: 여러 주제를 직접 다뤄보며, 코드와 구조에서 확인한 내용을 정리합니다.
url: "https://liamkim-daeyong.github.io"
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul

theme: minima
plugins:
  - jekyll-feed

show_drafts: false
show_excerpts: true
permalink: /:year/:month/:day/:title/
header_pages:
  - about.md

exclude:
  - README.md
